# Generated by Django 4.1 on 2022-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_planets_diameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsystem',
            name='planets',
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='planets',
            field=models.ManyToManyField(to='main.planets'),
        ),
    ]
