# Generated by Django 4.1 on 2022-08-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_solarsystem_planets_solarsystem_planets'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarsystem',
            name='acceleration',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='circumference',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='diameter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='mass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
