# Generated by Django 4.1 on 2022-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_solarsystem_acceleration_solarsystem_circumference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('circumference', models.FloatField(max_length=100, null=True)),
                ('acceleration', models.FloatField(max_length=100, null=True)),
                ('mass', models.CharField(blank=True, max_length=200, null=True)),
                ('diameter', models.CharField(blank=True, max_length=200, null=True)),
                ('distance', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='planets',
            name='distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solarsystem',
            name='stars',
            field=models.ManyToManyField(to='main.stars'),
        ),
    ]
