# Generated by Django 4.1 on 2022-08-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stars_planets_distance_solarsystem_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='stars',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
