# Generated by Django 4.1 on 2022-08-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_planets_exo_planet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarsystem',
            name='acceleration',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solarsystem',
            name='circumference',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
