# Generated by Django 4.1 on 2022-08-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_solarsystem_acceleration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarsystem',
            name='acceleration',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='circumference',
        ),
        migrations.RemoveField(
            model_name='solarsystem',
            name='diameter',
        ),
    ]
