# Generated by Django 4.1 on 2022-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_solarsystem_acceleration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='period',
            field=models.CharField(default=0.241, max_length=100),
        ),
    ]
