# Generated by Django 4.1 on 2022-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_planets_distance_alter_planets_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planets',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
